# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "hello, qa world !!!"

  displayName: 'Run a multi-line script'



- powershell: echo "echo "helloworld" " | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/helloworld.txt

- powershell: Rename-Item -Path  $env:BUILD_ARTIFACTSTAGINGDIRECTORY/helloworld.txt -NewName "helloworld.bat"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop


      