# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- powershell: echo ".\mah.exe generate-tokens -s d5c9bbc0-276b-4d1a-ae2a-a42ff18a3f3c -i cb447b8e-c655-e911-b49e-000d3a1027a1" | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/generate_tokens.txt

- powershell: Rename-Item -Path  $env:BUILD_ARTIFACTSTAGINGDIRECTORY/generate_tokens.txt -NewName "generate_tokens.bat"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop


      